### ISSUE TITLE
Improve Orangebox API

### ISSUE THREAD

**Issue by mixflame** [jsilverMDX/orangebox#3]
Current use array of arrays is.. well, ugly.

Change the API in these ways:
- use camelCase
- use an object instead of Array of Arrays
- begin function with a capital letter since it is global

**Comment by kfatehi** [comment]
I'd say make your object OrangeBox and then make people use it like OrangeBox.showMsg({opts}), OrangeBox.hideMsg() :+1:

**Comment by mixflame** [comment]
Good idea. Will do!

**Comment by mixflame** [comment]
fixed.
